language: scala
sudo: false

jdk:
  - oraclejdk8
scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2
matrix:
  include:
    - scala: 2.10.6
      jdk: openjdk7

# Taken from https://github.com/typelevel/cats/blob/master/.travis.yml
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
